version: 2 

sources:
  - name: raw_data
    description: "Raw data sources for NYC taxi rides"
    database: modular-magpie-485005-j6
    schema: data_ride_ny
    tables:
     - name: yellow_tripdata
     - name: green_tripdata